### ISSUE TITLE
pmm-admin can't add multi mysql port in single machine

### ISSUE THREAD

**Issue by linuxgood1230** [percona/pmm-client#16]

**Comment by roman-vynar** [comment]
There is `--port` MySQL flag. See `pmm-admin add mysql:metrics --help`.

**Comment by linuxgood1230** [comment]
# pmm-admin list
pmm-admin 1.0.5

PMM Server      | 10.10.10.100
Client Name     | ai-d30.zw
Client Address  | 10.30.10.30
Service manager | unix-systemv

-------------- ---------- ------------ -------- ----------------------------- ---------------------
SERVICE TYPE   NAME       CLIENT PORT  RUNNING  DATA SOURCE                   OPTIONS              
-------------- ---------- ------------ -------- ----------------------------- ---------------------
linux:metrics  ai-d30.zw  42000        YES      -                                                  
mysql:queries  ai-d30.zw  42001        YES      orch:***@tcp(127.0.0.1:3321)  query_source=slowlog 
mysql:metrics  ai-d30.zw  42002        YES      orch:***@tcp(127.0.0.1:3321)  tablestats=OFF

-----------
# pmm-admin add mysql:metrics --user=orch --host=127.0.0.1 --password=password --port=3318
Error adding MySQL metrics: there is already one instance with this name under monitoring.

**Comment by linuxgood1230** [comment]
have a Error  return

**Comment by roman-vynar** [comment]
You need to name instance differently.
By default, the instance takes a name of the client, in your case `ai-d30.zw`.

You have already one mysql:metrics instance with that name.
If you want to add another mysql:metrics instance specify the name in the end.
For example:
```
pmm-admin add mysql:metrics --user=orch --host=127.0.0.1 --password=password --port=3318 NAME
```
where NAME is an instance name.

**Comment by linuxgood1230** [comment]
Maybe the name can be auto generate by host:port

**Comment by roman-vynar** [comment]
Good suggestion, thanks! We will think about it.
