### ISSUE TITLE
grafana show Buffer pool size of total ram no value

### ISSUE THREAD

**Issue by linuxgood1230** [percona/pmm-client#17]
grafana show Buffer pool size of total ram no value

Now: now export has a name,default hostname
when i have two mysql instances .I'd like to  one export has it's only name
like
linux :  $hostname
mysql port 3306:  3306:${hostname}
mysql port 3307:  3307:${hostname}

I guess, Total buffer size of total RAM . 
one mysql instance  must has a linux export, and they are name must be the same;

then, the mysql instances can show corrent  buffer size of  Total RAM in grafana

**Comment by roman-vynar** [comment]
Correct, we match by name and for other MySQL instances on the same machine, it won't show %.
