### ISSUE TITLE
Proxying Consul to an External Consul Instance

### ISSUE THREAD

**Issue by wfortin136** [percona/pmm-client#22]
We are running the pmm-server in Kubernetes. We already have instances of Prometheus, Grafana, and Consul running outside of the pmm-server. In the act of centralizing our monitoring and metrics, we have attempted to proxy the apps (specifically in this case, consul) to our external running consul app. We have done this successfully by altering the nginx configuration. However, the following line presents an issue, as our cluster leader is not running on localhost. 

https://github.com/percona/pmm-client/blob/master/pmm/main.go#L146

As expected, due to leader != "127.0.0.1:8300", our pmm client complains with the following error:

Unable to connect to PMM server by address: pmm.vividseats.test

Even though the server is reachable it does not look to be PMM server.
Check if the configured address is correct.

When we call <pmm-server-address>/v1/status/leader, we return a valid ip of our pmm server, "xxx.xx.xx.x:8300"

Could the code base be updated to not enforce this localhost constraint?

**Comment by arvenil** [comment]
This will be fixed in pmm-client 1.1.4

**Comment by michaelcoburn** [comment]
Hi @wfortin136 , did you have a chance to use the 1.1.4 build in your environment? Can you confirm Consult is now working as expected?

**Comment by wfortin136** [comment]
@michaelcoburn I have not just yet. I may be able to give it a try by the end of the week and can report back.
