### ISSUE TITLE
tls: first record does not look like a TLS handshake

### ISSUE THREAD

**Issue by geraldcheng** [percona/pmm-client#28]
time="2017-02-28T16:32:34+08:00" level=info msg="HTTPS/TLS is enabled" source="mysqld_exporter.go:724"
time="2017-02-28T16:32:34+08:00" level=info msg="Listening on 192.168.67.23:42002" source="mysqld_exporter.go:727"
2017/02/28 16:33:47 http: TLS handshake error from 192.168.67.23:43970: tls: first record does not look like a TLS handshake
2017/02/28 16:34:58 http: TLS handshake error from 192.168.67.23:44018: tls: first record does not look like a TLS handshake
^C

something wrong?

**Comment by delgod** [comment]
you can found answer on Percona Forum https://www.percona.com/forums/questions-discussions/percona-monitoring-and-management/46674-tls-handshake-error?p=46679#post46679
