### ISSUE TITLE
Errors when percona specific tables do not exist

### ISSUE THREAD

**Issue by adc-jglick** [percona/pmm-client#4]
PMM Client version: pmm-admin 1.0.2
MySQL Server version: 5.6.21 MySQL Community Server (GPL)

I'm running MySQL Community edition and because it doesn't contain some of the Percona specific tables, it's logging the following errors.  It would be helpful if the exporter would recognize that this table doesn't exist on all versions of MySQL.

`time="2016-07-29T16:30:54-05:00" level=error msg="Error scraping for collect.info_schema.userstats: Error 1109: Unknown table 'user_statistics' in information_schema" source="mysqld_exporter.go:353"
time="2016-07-29T16:30:54-05:00" level=error msg="Error scraping table stat: Error 1109: Unknown table 'table_statistics' in information_schema" source="mysqld_exporter.go:359"`

**Comment by roman-vynar** [comment]
Thanks.

It will suppressed once we update the exporter on PMM Client.
The fix on mysqld_exporter level is done here https://github.com/prometheus/mysqld_exporter/pull/149
