### ISSUE TITLE
pmm-client can't get the password from the defaults-file on MySQL 5.7

### ISSUE THREAD

**Issue by isartmontane-socialbro** [percona/pmm-client#5]
Hello,

there seems to be an issue when trying to use the `--defaults-file` option on the `pmm-admin` command when trying to monitor a MySQL 5.7.

Even when the right password is set on the defaults file it reports that it's wrong:
```
# pmm-admin add mysql --defaults-file /root/.my.cnf
[MySQL] 2016/08/03 21:54:26 packets.go:118: write unix @->/data/mysql/mysql.sock: write: broken pipe
Cannot connect to MySQL: Error 1045: Access denied for user 'root'@'localhost' (using password: YES)

Verify that MySQL user exists and has the correct privileges.
Use additional MySQL flags --user, --password, --host, --port, --socket if needed.
```

But if I use the MySQL command line it works fine
```
# mysql --defaults-file=/root/.my.cnf
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 995
Server version: 5.7.13-6-log Percona Server (GPL), Release '6', Revision 'e3d58bb'

Copyright (c) 2009-2016 Percona LLC and/or its affiliates
Copyright (c) 2000, 2016, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> 
```

I've traced the error back to the `go-mysql` library that `pmm-client` is using to get the DSN. The `go-mysql` gets the DSN trough the output of `mysql --defaults-file=FILE --print-defaults`, but on MySQL 5.7 that prints the password masked with `*`

```
# mysql --defaults-file=/root/.my.cnf --print-defaults
mysql would have been started with the following arguments:
--user=root --password=***** --socket=/data/mysql/mysql.sock 
```
On MySQL 5.7 that needs to be replaced with a call to `my_print_defaults`
```
# my_print_defaults -s client mysql
--user=root
--password=MyPassWorD
--socket=/data/mysql/mysql.sock
```

On previous versiones (at least on 5.6) what `go-mysql` is doing seems to be working OK, but I couldn't make it work on 5.7

```
# mysql --defaults-file=/root/.my.cnf  --print-defaults
mysql would have been started with the following arguments:
-socket=/data/mysql/mysql.sock --user=root --password=MyPassWorD
```

Thats the affected line on the `go-mysql`
https://github.com/percona/go-mysql/blob/master/dsn/dsn.go#L120

I should probably report the issue under the `go-mysql` project, but I don't see the tab to open issues there.

**Comment by percona-csalguero** [comment]
Hi @isartmontane-socialbro ,

Thanks for such a detailed error report.
You are right, according to the [documentation ](http://dev.mysql.com/doc/refman/5.7/en/option-file-options.html#option_general_print-defaults) 

> As of MySQL 5.7.8, password values are masked

I am opening an internal error report to fix this.

Regards

**Comment by percona-csalguero** [comment]
Fix submited: https://github.com/percona/go-mysql/pull/19/files
