### ISSUE TITLE
add --instancename (or something similar) to pmm-admin

### ISSUE THREAD

**Issue by miguelangel-percona** [percona/pmm-client#9]
This is a feature request from one of our users/customers:

> Can I suggest adding a feature enhancement to get the instanceName as a parameter: eg:
> 
> [root@sandbox ~]# pmm-admin add mysql:metrics --user root --password msandbox --host 127.0.0.1 --port 5172 --create-user --instancename db1
> 
> I think this would be clearer and you would automatically include it in the documentation much as you've documented the other flags.

**Comment by vadimtk** [comment]
@miguelangel-percona  can you create issue in https://jira.percona.com/browse/PMM ?
We do not use GitHub for issues.
